### ISSUE TITLE
ProjectInitialize resource does not update after initial application

### ISSUE THREAD

**Issue by ddeno** [redhat-cop/project-initialize-operator#11]
After applying the following `ProjectInitialize` resource, saved as PI.yaml, using `oc apply -f PI.yaml`:

```
apiVersion: redhatcop.redhat.io/v1alpha1
kind: ProjectInitialize
metadata:
  name: test-namespace-1234b
spec:
  cluster: us-east-1.example.opentlc.com
  desc: ''
  displayName: Test Namespace
  env: production
  namespaceDetails:
    annotations:
      koncierge.io/quota: small
      koncierge.io/rolebindings: admin:view
    labels:
      app: koncierge
      component: server
      version: 0.0.1
  quotaSize: small
  team: backend-dev
```

All resources are created properly; however, if you want to update information such as the following items:

* `spec.cluster`
* `spec.desc`
* `spec.displayName`
* `spec.production`
* `spec.team`

by updated that `PI.yaml` file and running `oc apply -f PI.yaml` again, the resource is not updated. According to https://github.com/redhat-cop/project-initialize-operator/blob/master/pkg/controller/projectinitialize/projectinitialize_controller.go#L150, the logic for these attributes is just missing at the moment.
