### ISSUE TITLE
ProjectInitialize resource cannot have explicit Name

### ISSUE THREAD

**Issue by ddeno** [redhat-cop/project-initialize-operator#12]
Request to make the following specification change for `ProjectInitialize` resource type:

### Current

Currently, the name for a namespace and project is create by way of `<spec.team>-<spec.env>`. This does not allow for a user to set a name if they wish.

```
apiVersion: redhatcop.redhat.io/v1alpha1
kind: ProjectInitialize
metadata:
  name: test-namespace-1234b
spec:
  cluster: us-east-1.example.opentlc.com
  desc: ''
  displayName: Test Namespace 3
  env: production
  namespaceDetails:
    annotations:
      koncierge.io/quota: small
      koncierge.io/rolebindings: admin:view
    labels:
      app: koncierge
      component: server
      version: 0.0.1
  quotaSize: small
  team: backend-dev
```

### Proposed

Update specification to allow for `spec.namespace.name`. This would allow for a user to set the name explicitly. Additionally, it could still default to `<spec.team>-<spec.env>` if `spec.namespace.name` is not specified. Also note that `namespaceDetails` is now just `namespace` as it is implied that attributes under `namespace` are details for it.

```
apiVersion: redhatcop.redhat.io/v1alpha1
kind: ProjectInitialize
metadata:
  name: test-namespace-1234b
spec:
  cluster: us-east-1.example.opentlc.com
  desc: ''
  displayName: Test Namespace 3
  env: production
  namespace:
    name: test-namespace-1234b
    annotations:
      koncierge.io/quota: small
      koncierge.io/rolebindings: admin:view
    labels:
      app: koncierge
      component: server
      version: 0.0.1
  quotaSize: small
  team: backend-dev
```
