### ISSUE TITLE
quota does not get applied if ProjectInitializeQuota is added after ProjectInitialize is created

### ISSUE THREAD

**Issue by gnekic** [redhat-cop/project-initialize-operator#4]
I found this behavior. It's somewhat of a corner case, but I think adding logic to handle it at some point would make sense.

I was playing with some order of operations and created a ProjectInitialize before creating the appropriate ProjectInitializeQuota. The operator throws this error: 
```
{"level":"info","ts":1586358358.1973412,"logger":"controller_projectinitialize","msg":"Reconciling ProjectInitialize","Request.Namespace":"","Request.Name":"example-projectinitialize"}                          
{"level":"error","ts":1586358358.6634288,"logger":"controller_quayecosystem","msg":"Quota definition not found: small","error":"ProjectInitializeQuota.redhatcop.redhat.io \"small\" not found","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/gnekic/git/project-initialize-operator/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/redhat-cop/project-initialize-operator/project-initialize/pkg/controller/projectinitialize/ocp/project.GetQuotaSizeFromCluster\n\t/home/gnekic/git/project-initialize-operator/pkg/controller/projectinitialize/ocp/project/quotas.go:29\ngithub.com/redhat-cop/project-initialize-operator/project-initialize/pkg/controller/projectinitialize.(*ReconcileProjectInitialize).Reconcile\n\t/home/gnekic/git/project-initialize-operator/pkg/controller/projectinitialize/projectinitialize_controller.go:122\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/gnekic/git/project-initialize-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/gnekic/git/project-initialize-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/home/gnekic/git/project-initialize-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/home/gnekic/git/project-initialize-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/gnekic/git/project-initialize-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/home/gnekic/git/project-initialize-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
{"level":"error","ts":1586358358.6635063,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"projectinitialize-controller","request":"/example-projectinitialize","error":"ProjectInitializeQuota.redhatcop.redhat.io \"small\" not found","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/gnekic/git/project-initialize-operator/vendor/github.com/go-logr/zapr/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/gnekic/git/project-initialize-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/gnekic/git/project-initialize-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/home/gnekic/git/project-initialize-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/home/gnekic/git/project-initialize-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/gnekic/git/project-initialize-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/home/gnekic/git/project-initialize-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
```

Maybe I didn't wait long enough after I created the ProjectInitializeQuota to let the operator apply it to the project. I restarted the operator to see if that would trigger it, but it found that the project existed and did nothing.
```
{"level":"info","ts":1586358690.1084354,"logger":"controller_projectinitialize","msg":"Reconciling ProjectInitialize","Request.Namespace":"","Request.Name":"example-projectinitialize"}                          
{"level":"info","ts":1586358690.1136522,"logger":"controller_quayecosystem","msg":"Found project test-dev"}

```
I then created a new project reffering to the now created ProjectInializeQuota, and it added it properly. Log output here: 
```
{"level":"info","ts":1586358937.7144792,"logger":"controller_projectinitialize","msg":"Reconciling ProjectInitialize","Request.Namespace":"","Request.Name":"nekic-projectinitialize"}                            
{"level":"info","ts":1586358938.1459012,"logger":"controller_quayecosystem","msg":"Created quota nekic-test-quota for namespace nekic-test-dev"}                                                                  
{"level":"info","ts":1586358938.1459234,"logger":"controller_quayecosystem","msg":"Created new project nekic-test-dev"}  
```

### Here are the configs I used.
First ProjectInitialize
```yaml
apiVersion: redhatcop.redhat.io/v1alpha1
kind: ProjectInitialize
metadata:
  name: example-projectinitialize
spec:
  team: test
  env: dev
  cluster: np1
  displayName: "Test Project"
  desc: "A test project for showing the functionality of the project initialize operator"
  quotaSize: small
```
Small ProjectInitializeQuota
```yaml
apiVersion: redhatcop.redhat.io/v1alpha1
kind: ProjectInitializeQuota
metadata:
  name: small
spec:
  hard:
    cpu: "5"
    memory: "10Gi"
    pods: "10"
```
Second ProjectInitializeQuota
```yaml
apiVersion: redhatcop.redhat.io/v1alpha1
kind: ProjectInitialize
metadata:
  name: nekic-projectinitialize
spec:
  cluster: np1
  desc: A test project for showing the functionality of the project initialize operator
  displayName: nekic Project
  env: dev
  quotaSize: small
  team: nekic-test
```
